.TH KKLONDIKE 6 "1992" "Kgames 1.0"
.SH NAME
kklondike \- X window klondike solitaire
.SH SYNOPSIS
.B kklondike
.SH DESCRIPTION
.I Kklondike
brings up a window for a klondike solatiaire game.
Clicking on a card moves it to the "best" legal play. Dragging a card
places it (if legal) in the target stack.
.SH RULES
Tableaus build down in alternating colors. Full or partial builds may
be moved among the tableaus. Empty tableaus may be filled with Kings
or with builds beginning with Kings.  The top card in the discard pile
may be played on tableaus or foundations.  Foundations build up in
suit from the Ace.
.P
Deal three cards onto the discard pile by clickingn the hand.
Click on the empty hand to move the discards back.
.P
Goal: move all cards to the foundations.
.SH AUTHOR
Keith Packard
