.TH KSLYFOX 6 "1992" "Kgames 1.0"
.SH NAME
kslyfox \- X window sly fox solitaire
.SH SYNOPSIS
.B kslyfox
.SH DESCRIPTION
.I Kslyfox
brings up a window for a sly fox solataire game.
Clicking on a card moves it to the "best" legal play. Dragging a card
places it (if legal) in the target stack.
.SH RULES
.P
Sly Fox is a double-deck solitaire game.
.P
4 Aces and 4 Kings (1 of each suit) is pulled out and used for
the foundations, with the Ace piles building up in suit and the
King piels building down.
.P
20 cards are dealt face up in 4 rows of 5 to form the reserve.
.P
Any of the reserve cards can be played on the foundations, and
the space formed by this is immediately filled in from the deck.
.P
Once no more plays can be made, cards are dealt one at a time from the
deck.  Each card can either be played to a foundation, or placed on one
of the 20 reserve stacks.  During this play, none of the reserve cards
can be moved to the foundations.  Once 20 cards have been added to the
reserve, the reserve cards can again be played as before, except that
spaces are not filled immediately, but instead left for the next deal.
.P
Playing the X version
.P
In general, clicking on a card will make it do the "right thing".
Cards can also be dragged between piles.
.P
To change between Deal play (when the reserve cards are in play) to
Reserve play (when the deck cards are being added to the reserve),
select 'Deal', hit the 'd' key or click on the deck.  Once 20 cards
are added to the reserve stacks, the game will revert to Deal mode.
.P
During Reserve play, simply clicking on the destination of the card in
play will place it there.
.SH AUTHOR
Keith Packard
