.TH KMCARLO 6 "1992" "Kgames 1.0"
.SH NAME
kmcarlo \- X window monte carlo solitaire
.SH SYNOPSIS
.B kmcarlo
.SH DESCRIPTION
.I Kmcarlo
brings up a window for a monte carlo solatiaire game.
Clicking on a card moves it to the "best" legal play. Dragging a card
places it (if legal) in the target stack.
.SH AUTHOR
Keith Packard
