.TH KCRIBBAGE 6 "1992" "Kgames 1.0"
.SH NAME
kcribbage \- X window cribbage game
.SH SYNOPSIS
.B kcribbage
.SH DESCRIPTION
.I Kcribbage
brings up a window for a cribbage game played against the computer.
Clicking on a card moves it to the "best" legal play. Dragging a card
places it (if legal) in the target stack. Use the keyboard to provide
answers for questions in the text window.
.SH AUTHOR
Keith Packard
