.TH KDOMINOS 6 "1992" "Kgames 1.0"
.SH NAME
kdominos \- X window dominos game against the computer
.SH SYNOPSIS
.B kdominos
.SH DESCRIPTION
.I Kdominos
brings up a window for a dominos game against the computer.
Drag dominos into position on the board or click one of the controls.
.SH AUTHOR
Keith Packard
