.TH KACES 6 "1992" "Kgames 1.0"
.SH NAME
kaces \- X window aces high solitaire
.SH SYNOPSIS
.B kaces
.SH DESCRIPTION
.I Kaces
brings up a window for a aces solatiaire game.
Clicking on a card moves it to the "best" legal play. Dragging a card
places it (if legal) in the target stack.
.SH RULES
Top cards of tableaus are available, and may be discarded if they
have the same suit and lower rank than another available card.
Empty tableaus may be filled with any available card. Aces
rank high, above Kings.
.P
Deal four more cards by clickping the deck. Dealing is not allowed
until empty tableaus have been filled (if possible).
.P
Goal: discard all cards except for the four Aces.
.SH AUTHOR
Keith Packard
